// <auto-generated />
using EuroScaffolding2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EuroScaffolding.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EuroScaffolding2.Models.Cancion", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identificador"));

                    b.Property<int>("EdFestivalId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identificador");

                    b.HasIndex("EdFestivalId");

                    b.ToTable("Canciones");
                });

            modelBuilder.Entity("EuroScaffolding2.Models.EdFestival", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identificador"));

                    b.Property<int>("Anyo")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identificador");

                    b.ToTable("EdFestivales");
                });

            modelBuilder.Entity("EuroScaffolding2.Models.Pais", b =>
                {
                    b.Property<int>("CancionIdentificador")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CancionIdentificador");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("EuroScaffolding2.Models.Cancion", b =>
                {
                    b.HasOne("EuroScaffolding2.Models.EdFestival", "EdFestival")
                        .WithMany("Canciones")
                        .HasForeignKey("EdFestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EdFestival");
                });

            modelBuilder.Entity("EuroScaffolding2.Models.Pais", b =>
                {
                    b.HasOne("EuroScaffolding2.Models.Cancion", "Cancion")
                        .WithOne("Pais")
                        .HasForeignKey("EuroScaffolding2.Models.Pais", "CancionIdentificador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancion");
                });

            modelBuilder.Entity("EuroScaffolding2.Models.Cancion", b =>
                {
                    b.Navigation("Pais")
                        .IsRequired();
                });

            modelBuilder.Entity("EuroScaffolding2.Models.EdFestival", b =>
                {
                    b.Navigation("Canciones");
                });
#pragma warning restore 612, 618
        }
    }
}
